language: php

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
 - sudo apt-get install -qq python-numpy python-scipy
 - pip install numpy

install:
  - composer install --prefer-source --no-interaction
  # PHPUnit
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require phpunit/phpunit 5.7.*; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then composer require phpunit/phpunit 5.7.*; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require phpunit/phpunit 6.1.*; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:4} == "hhvm" ]]; then composer require phpunit/phpunit; fi
  - ./vendor/bin/phpunit --version

script:
  # Run PHP unit tests
  - ./vendor/bin/phpunit -c test/Unit/phpunit.xml.dist
  # Run benchmark tests
  - ./test/Benchmark/bench.sh

after_script:
  ## Code climate
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/test-reporter; fi
