language: php

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - sudo apt-get update && apt-get upgrade -y && apt-get install openssl
  - composer install
  - phpunit --self-update

script: phpunit -c test/Unit/phpunit.xml.dist

after_script:
  ## Code climate
  - ./vendor/bin/test-reporter
